# Site
repository: 42Joe/modern-resume-theme
version: 2

# Personal info
name: Joe Schneider
title: Personal website
email: email@josef-schneider.org
phone: "+43 699 194 22 014"
website: josef-schneider.org

# Social links
github_username: 42Joe
linkedin_username: josef-schneider-27435743
orcid_username: 0000-0002-8550-2952

# Additional icon links
additional_links:
  - title: Mastodon
    icon: fab fa-mastodon
    url: https://graz.social/@joe42

# About Section
about_profile_image: images/joe # PRÜFEN: Endung .jpg oder .png ergänzen
about_content: |
  I am a **hydraulic engineer** working at Graz University of Technology. In addition to my role as Deputy Head of the Institute, I also serve as the Head of Laboratory at the Institute of Hydraulic Engineering and Water Resources Management.
  
  In my professional work, I focus on **fluvial morphology** and **hydropower development**. Previously, my work focused primarily on **sediment transport** and **reservoir sedimentation**. A key emphasis of my research was the assessment of sediment flushing and sluicing operations through dams and reservoirs to prevent sedimentation. 
  
  Consequently, I am continuously involved in the development of new hydropower plants as well as the retrofitting of existing facilities. I oversee these projects as a **project manager**, primarily utilizing physical scale model tests at our institute. Recently, I have also been increasingly involved in **fish migration**, specifically studying movement in both upstream and downstream directions. A recently completed example is briefly presented below.

  [**Download my Short CV (PDF)**](assets/pdfs/2025_shortCV_joe.pdf)

content:
  - title: Projects
    layout: list
    content:
      - layout: right
        border: weak
        title: Downstream fish migration
        link: https://link.springer.com/article/10.1007/s00506-025-01154-8
        quote: >
          FFG Collective Research project on fish movement and hydropower impacts.
        description: |
          Research on downstream fish migration at hydropower plants remains critical. This FFG Collective Research project **Flussabwärts gerichtete Fischwanderung an mittelgroßen Fließgewässern in Österreich** (*Downstream fish migration in medium-sized watercourses in Austria*) used telemetry to track potadromous species in medium-sized rivers, finding that downstream movement occurs primarily via turbines and fish passes. Using Balloon Tags and Barotrauma Detection Systems (BDS), the study recorded physical stressors (pressure gradients, acceleration) and injury rates. These findings, combined with CFD and blade strike modeling as well as barochamber tests, provided the basis for age-class population modeling to assess the long-term impacts of hydropower passage.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: University of Natural Resources and Life Sciences (BOKU), Vienna
        sub_title: Research Assistant
        caption: 1998 - 2002
        description: |
          * Research focus on sediment transport and reservoir sedimentation. 
          * Meteorological and hydrological field measurements.
      - layout: right
        title: Graz University of Technology
        sub_title: Lab Manager & Deputy Head of Institute
        caption: 2003 - present
        link: https://hydro.tugraz.at
        description: |
          * Conducting hydraulic scale model tests.
          * Managing national and international research projects.
          * University lecturing and supervision of Bachelor, Master, and PhD students.
          + Deputy Head of Institute (since 2020) and Head of Laboratory (since 2009). 
          
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: PhD at BOKU, Vienna
        caption: 2002
        description: Doctoral studies in the field of hydraulic engineering.

      - layout: top-right
        title: Habilitation at TU Graz
        caption: 2018
        description: Post-doctoral lecture qualification (Venia Docendi) for "Hydraulic Engineering".

  - title: A Little More About Me
    layout: text
    content: |
      In addition to my work, I stay active to keep fit, play the drums, and enjoy reading. I also have 
      a personal interest in home automation and IT. For principled reasons, I avoid proprietary software and banished Microsoft 
      products  (*Therefore, I host this site on github* 😉.) from my computers and other devices years ago. 
      
      By the way, 2026 will certainly be the **year of the Linux desktop**.

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
